alias open='explorer'
alias c='clear'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../../..'
alias .4='cd ../../../../..'
alias .5='cd ../../../../../..'
alias ls='ls --color=auto'
alias reboot='Shutdown.exe -r -t 00'
alias shutdown='Shutdown.exe -s -t 00'
